ENV["YELP_CONSUMER_KEY"] = "iv2hZ5r24Xxj-67HFiBG9A"
ENV["YELP_CONSUMER_SECRET"] = "_rXFWGc3mXXE4Wr15FlvObsKOss"
ENV["YELP_TOKEN"] = "652i_mFPJIofjxh-MU_6NLGct_13SXrd"
ENV["YELP_TOKEN_SECRET"] = "r5fWuNAEKKN_ZnaX07eExLPR7rE"

